### PR TITLE
Set example accesskey and secretkey names to same as the secret example

### PR DESCRIPTION
**Pull request by mikkeschiren**
Just to simplify setup for "copy paste setups"

### CODE REVIEW

**Comment by Ilyesbdlala** [comment]
Thank you for Contribution :) Can you please clarify what you mean by "copy paste setups" ?

**Comment by mikkeschiren** [comment]
@Ilyesbdlala - just refering to if you use the example text in the values file - a.k.a. "copy paste" :)

**Comment by mikkeschiren** [comment]
The values file has this:
```
  # Example creation via kubectl:
  # kubectl create secret generic my-secret --from-literal=accessKey="******" --from-literal="secretKey=******"
  ```
  So just changing to the same case.

**Comment by Ilyesbdlala** [comment]
@mikkeschiren Has your issue been resolved? Or does the solution I suggested work for you ?

**Comment by Ilyesbdlala** [comment]
We decided on fixing the comment instead of the actual attributes https://github.com/secureCodeBox/secureCodeBox/pull/1839. Hope this resolves the issue.

**Pull request closed without merging**
