### PR TITLE
Slight refactor of scbctl

### PR DESCRIPTION
**Pull request by ddddddO**
## Description

Refactor scbctl👍!
- Remove extra processing in scbctl cmd's buildTree function ( https://github.com/secureCodeBox/secureCodeBox/pull/2682/commits/80f408b86186e72d2c279542d012f01c15d12f2e )
- Replace Map to Slice ( https://github.com/secureCodeBox/secureCodeBox/pull/2682/commits/1e1ac14476f29d3b3757d27c9a1c097c320a7ae8 )
  - Golang's map does not guarantee ordering, so I changed it from a map to a slice so that the result of each execution is the same each time.
  - I think it will solve the [problem](https://github.com/secureCodeBox/secureCodeBox/pull/2665#issuecomment-2359292320).
  - The following is a log of multiple runs of go test before and after the change at local.

    Before
    ```console
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.027s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.021s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.019s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.020s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    --- FAIL: TestBuildTree (0.00s)
        --- FAIL: TestBuildTree/Complex_cascade (0.00s)
            cascading_test.go:125: 
                    Error Trace:    /home/ddddddo/github.com/ddddddO/secureCodeBox/scbctl/cmd/cascading_test.go:125
                    Error:          Not equal: 
                                    expected: "Scans\n└── root\n    ├── child1\n    │   └── grandchild\n    └── child2\n"
                                    actual  : "Scans\n└── root\n    ├── child2\n    └── child1\n        └── grandchild\n"
                                
                                    Diff:
                                    --- Expected
                                    +++ Actual
                                    @@ -2,5 +2,5 @@
                                     └── root
                                    -    ├── child1
                                    -    │   └── grandchild
                                    -    └── child2
                                    +    ├── child2
                                    +    └── child1
                                    +        └── grandchild
                                     
                    Test:           TestBuildTree/Complex_cascade
    🆕 Creating a new scan with name 'nmap' and parameters 'scanme.nmap.org'
    🚀 Successfully created a new Scan 'nmap'
    🆕 Creating a new scan with name 'nmap' and parameters 'scanme.nmap.org -p 90'
    🚀 Successfully created a new Scan 'nmap'
    🆕 Creating a new scan with name 'scanme-nmap-org' and parameters 'scanme.nmap.org'
    🚀 Successfully created a new Scan 'scanme-nmap-org'
    🆕 Creating a new scan with name 'nmap' and parameters 'scanme.nmap.org'
    🚀 Successfully created a new Scan 'nmap'
    🆕 Creating a new scan with name 'kubeaudit' and parameters '--namespace some-other-namespace'
    🚀 Successfully created a new Scan 'kubeaudit'
    Error: you must use '--' to separate scan parameters
    Error: you must use '--' to separate scan parameters
    triggered new Scan for ScheduledScan 'nmap'
    Error: could not find ScheduledScan 'nonexistent-scan' in namespace 'foobar'
    Error: accepts 1 arg(s), received 0
    triggered new Scan for ScheduledScan 'nmap'
    FAIL
    FAIL    github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.025s
    FAIL
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$
    ```
    
    ↓
    
    After
    ```console
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.019s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.019s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.025s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.023s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.017s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.025s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.019s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.034s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.019s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.021s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.023s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.022s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.024s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.020s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.018s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.026s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./... -count=1
    ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       0.021s
    ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$
    ```

### Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.

  ```console
  ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$ go test ./...
  ok      github.com/secureCodeBox/secureCodeBox/scbctl/cmd       (cached)
  ddddddo@debian:~/github.com/ddddddO/secureCodeBox/scbctl/cmd$
  ```

* [x] Make sure that all your commits are signed-off and that you are added to the [Contributors](https://github.com/secureCodeBox/secureCodeBox/blob/main/CONTRIBUTORS.md) file.
* [ ] Make sure that all CI finish successfully.
* [x] Optional (but appreciated): Make sure that all commits are [Verified](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### CODE REVIEW

**Comment by ddddddO** [comment]
@J12934 
Hi! 
Please review this issue as I think it will resolve [this problem](https://github.com/secureCodeBox/secureCodeBox/pull/2665#issuecomment-2359292320)👍

**Comment by ddddddO** [comment]
fyi @Freedisch 

Hi!
I have made a few changes to the source code🙇

**Comment by J12934** [comment]
Hi @ddddddO

Thank you for taking a deeper look at this 🙌

Can you add yourself to the contributors file: https://github.com/secureCodeBox/secureCodeBox/blob/main/CONTRIBUTORS.md

Then we should be ready to merge 😊

**Comment by ddddddO** [comment]
@J12934 

Thanks for the review!
And thanks for putting my name on the CONTRIBUTORS.md even though it is a small code change!

**Comment by J12934** [comment]
The nikto test failures like 99.99% unrelated to this. Will try restarting it, will take a look at them if that doesn't help

**Comment by ddddddO** [comment]
It looks like this test is not failing on any commit other than this PullRequest... It's a mystery...

**Comment by J12934** [comment]
@ddddddO had a look regarding the nikto issues :)
Think i found a workaround: https://github.com/secureCodeBox/secureCodeBox/pull/2685

**Comment by ddddddO** [comment]
@J12934 
Excellent🎉! Thank you!

**Review by J12934 — APPROVED** [review]

**Comment by J12934** [comment]
Ok build now went through after a second fix 😊

Merge the PR now. Thanks again for the contribution and the patience 😅

**Comment by ddddddO** [comment]
I saw https://github.com/sullo/nikto/issues/843👍 Thank you very much!

**Pull request merged**
