### PR TITLE
Issue 1353 make fails spaces in path

### PR DESCRIPTION
**Pull request by Weltraumschaf**
## Description

We do not allow white spaces in any path (inside the repo) ans also from outside. A checkout lie `git checkout ... secure\ Code\ Box` will not work due to limitations of GNU Make. workaround is to stop script with a hopefully helpful message.

This PR also cleans up some other stuff in Makefile (see commit messages).

Not fixed: Free BSD. Make from FreeBSD complains about lot of things:

```
make: "/root/src/secureCodeBox/common.mk" line 24: Invalid line type
make: "/root/src/secureCodeBox/common.mk" line 25: Invalid line type
make: "/root/src/secureCodeBox/common.mk" line 26: Invalid line type
...
```

Almost always ifeq/ifdef outside recipe. Since there is no docker available for FreeBSD which is a mandatory prerequisite to build -> Won't fix.

### Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] Make sure that all your commits are signed-off and that you are added to the [Contributors](https://github.com/secureCodeBox/secureCodeBox/blob/main/CONTRIBUTORS.md) file.
* [x] Make sure that all CI finish successfully.
* [ ] Optional (but appreciated): Make sure that all commits are [Verified](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### CODE REVIEW

**Review by malexmave — COMMENTED** [review]
Confirmed that `make create-new-scanner NAME=name` works with this. Other Make targets will probably still fail (@rebeccan is the expert on failing make commands 😁)

**Review by malexmave — DISMISSED** [review]
Since this breaks the CI with syntax errors on makefile execution, I can trivially say that this needs changes 😁

**Comment by Weltraumschaf** [comment]
> Since this breaks the CI with syntax errors on makefile execution, I can trivially say that this needs changes 😁

Was a copy&paste bug. Fixed.

**Comment by the-simmon** [comment]
I cloned this branch into a folder called `/tmp/test\ with\ spaces/` then executed `make test` in the operator folder. This was the result:
```
Makefile:181: Warnung: Die Befehle für das Ziel „/tmp/test“ werden überschrieben
Makefile:166: Warnung: Alte Befehle für das Ziel „/tmp/test“ werden ignoriert
Makefile:181: Warnung: Die Befehle für das Ziel „with“ werden überschrieben
Makefile:166: Warnung: Alte Befehle für das Ziel „with“ werden ignoriert
Makefile:186: Warnung: Die Befehle für das Ziel „/tmp/test“ werden überschrieben
Makefile:181: Warnung: Alte Befehle für das Ziel „/tmp/test“ werden ignoriert
Makefile:186: Warnung: Die Befehle für das Ziel „with“ werden überschrieben
Makefile:181: Warnung: Alte Befehle für das Ziel „with“ werden ignoriert
Makefile:191: Warnung: Die Befehle für das Ziel „/tmp/test“ werden überschrieben
Makefile:186: Warnung: Alte Befehle für das Ziel „/tmp/test“ werden ignoriert
Makefile:191: Warnung: Die Befehle für das Ziel „with“ werden überschrieben
Makefile:186: Warnung: Alte Befehle für das Ziel „with“ werden ignoriert
make: Zirkuläre Abhängigkeit /tmp/test <- /tmp/test wird nicht verwendet.
make: Zirkuläre Abhängigkeit with <- /tmp/test wird nicht verwendet.
make: Zirkuläre Abhängigkeit with <- with wird nicht verwendet.
mkdir -p /tmp/test with spaces/operator/bin
make: Zirkuläre Abhängigkeit with <- /tmp/test wird nicht verwendet.
make: Zirkuläre Abhängigkeit with <- with wird nicht verwendet.
make: Zirkuläre Abhängigkeit with <- /tmp/test wird nicht verwendet.
make: Zirkuläre Abhängigkeit with <- with wird nicht verwendet.
test -s /tmp/test with spaces/operator/bin/setup-envtest || GOBIN=/tmp/test with spaces/operator/bin go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
bash: Zeile 1: test: Zu viele Argumente.
bash: Zeile 1: with: Kommando nicht gefunden.
make: *** [Makefile:191: with] Fehler 127
```

Is this the desired behavior? Tested on Arch linux.

**Comment by Weltraumschaf** [comment]
I missed some Makefiles deep in the module structure. Now all Makefiles test for spaces in the path.

**Review by malexmave — DISMISSED** [review]

**Pull request merged**
