### PR TITLE
Cascading Scans: rename directory & docker containers

### PR DESCRIPTION
**Pull request by EndPositive**
## Description
This PR renames declarative-subsequent-scans to cascading-scans wherever possible.
This PR is part of the maintenance for v3.0.0 as described in #293. 

This PR will not introduce the hook- prefix for the docker container as described in #471 .

## Todo
* [x] Rename docker containers, directory name, and helm chart name.
* [x] Rename code references.
* [x] Rename test usages.

### Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] Make sure `npm test` runs for the whole project.
* [x] Make codeclimate checks happy

### CODE REVIEW

**Comment by EndPositive** [comment]
Codeclimate isn't happy, but the errors are unrelated to this PR.

**Comment by J12934** [comment]
Awesome 🚀 Will take a look at it later.

> Codeclimate isn't happy, but the errors are unrelated to this PR.

Yeah it sometimes does that 😕
We can still merge it, no problem

**Comment by EndPositive** [comment]
Codeclimate is fixed in #482 !

**Comment by J12934** [comment]
This should now be rebased / have `main` merged into it to apply the fixes for code climate.

**Comment by EndPositive** [comment]
Done 😃

**Review by J12934 — APPROVED** [review]

**Pull request merged**
