### PR TITLE
[SCB-Bot] Upgraded amass from v3.23.1 to v3.22.2

### PR DESCRIPTION
**Pull request by secureCodeBoxBot**
This is an automated Pull Request by the SCB-Bot. It upgrades amass from v3.23.1 to v3.22.2
### Release changes : [here](https://github.com/OWASP/Amass/releases/v3.22.2)

### CODE REVIEW

**Comment by Weltraumschaf** [comment]
@Ilyesbdlala @J12934 Is this a "downgrade"?

**Comment by Ilyesbdlala** [comment]
> @Ilyesbdlala @J12934 Is this a "downgrade"?

I am not sure. SCB-Bot looks at https://github.com/owasp-amass/amass/releases and gets the latest version. This shows that it is v3.22.2. But v3.23.1 obviously exists https://github.com/owasp-amass/amass/releases/tag/v3.23.1. @Weltraumschaf Is it possible that the release "tag" was removed accidentally in the GitHub UI or due to a bug? It happened to other repos as well, https://github.com/secureCodeBox/secureCodeBox/pull/1658. I am not familiar with the mechanism that makes a git tag a release in the releases tab.

**Comment by J12934** [comment]
@Ilyesbdlala 
Tags can exist on GitHub without a release. When you Tag something from the cli and push the tag it'll exist on GitHub without a associated release

**Comment by Ilyesbdlala** [comment]
> @Ilyesbdlala Tags can exist on GitHub without a release. When you Tag something from the cli and push the tag it'll exist on GitHub without a associated release

We upgraded to v3.23.1. This means the release existed earlier. My question is : are we sure that the release was removed intentionally from the releases tab? Because this also happened with kubeaudit last week, and I find it unlikely that they would both simply remove a release, instead of creating a patch release etc..

**Comment by J12934** [comment]
Yes we Upgrades, but manually. I don't think the "GitHub release" ever existed. Just the tags

**Comment by Ilyesbdlala** [comment]
> Yes we Upgrades, but manually. I don't think the "GitHub release" ever existed. Just the tags

Ah yes I forgot that it wasn't done with the bot but instead here https://github.com/secureCodeBox/secureCodeBox/commit/4e88e87dfb90cbe75a31bd02783b7d05e86561b3 (I have the memory of a goldfish :sweat_smile:) :  
I guess we'll keep this PR open, to keep the bot from creating a new one. Maybe I should add some version lower/higher comparison to the bot, but it seemed not worth the trouble at the time.

**Comment by Weltraumschaf** [comment]
So we should close this PR?

**Comment by Ilyesbdlala** [comment]
> So we should close this PR?

No, In that case, it will be opened again by the bot. The bot looks at the open PRs (drafts included), to see if the PR already exists. (As seen here:)
https://github.com/secureCodeBox/secureCodeBox/blob/f5441f8636804c7b7f3745319df613cd38d26a04/.github/workflows/scb-bot.yaml#L122
@J12934 and I compromised on letting this PR open but as a draft,  to stop the bot from opening new ones and also letting it be known that the PR should not be merged.
This should no longer be an issue in the future, as long as amass does not fail up their release again ^_^

**Comment by Ilyesbdlala** [comment]
> > So we should close this PR?
> 
> No, In that case, it will be opened again by the bot. The bot looks at the open PRs (drafts included), to see if the PR already exists. (As seen here:)
> 
> https://github.com/secureCodeBox/secureCodeBox/blob/f5441f8636804c7b7f3745319df613cd38d26a04/.github/workflows/scb-bot.yaml#L122
> 
> @J12934 and I compromised on letting this PR open but as a draft, to stop the bot from opening new ones and also letting it be known that the PR should not be merged.
> This should no longer be an issue in the future, as long as amass does not fail their release again ^_^

Workaround no longer needed due to Amass upgrading to version  [v3.23.2](https://github.com/owasp-amass/amass/releases/tag/v3.23.2)

**Pull request closed without merging**
