### PR TITLE
Updates sslyze to latest release v4.1.0

### PR DESCRIPTION
**Pull request by rseedorff**
## Description

This PR if applied updates sslyze to latest release v4.1.0. More informations about this release are documented here: https://github.com/nabla-c0d3/sslyze/releases/tag/4.1.0

WIP due to missing docker images :-/ Added an issue to fix that: https://github.com/nabla-c0d3/sslyze/issues/521

### Checklist

* [ ] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [ ] Make sure `npm test` runs for the whole project.
* [ ] Make codeclimate checks happy

### CODE REVIEW

**Review by fuhrmeistery — APPROVED** [review]

**Comment by fuhrmeistery** [comment]
Maybe we should consider adding the Container Image to those we build our self

**Comment by Ilyesbdlala** [comment]
After reading the issue you linked, i see that the 4.1.0 docker image has been released thanks to you (Nice :ok_hand:). But it's been wrongly tagged as `sha-7e16dc0`. The author however plans to fix this in the next releases. Would I then suggest changing the scanner image tag in the values.yaml files to `sha-7e16dc0` for the time being. It seems to be set currently to a year old "sha" image tag.

**Comment by malexmave** [comment]
Can this PR be closed, since sslyze is being upgraded to an even newer version in another PR?

**Comment by Weltraumschaf** [comment]
Won't merge, we have a more current PR.

**Pull request closed without merging**
