### PR TITLE
Disable cascading rules by default

### PR DESCRIPTION
**Pull request by the-simmon**
solves #914

### CODE REVIEW

**Comment by malexmave** [comment]
Don't forget to also change the [template](https://github.com/secureCodeBox/secureCodeBox/blob/main/.templates/new-scanner/values.yaml#L94) and double-check the [example files in the documentation](https://www.securecodebox.io/docs/contributing/integrating-a-scanner/values.yaml).

**Comment by malexmave** [comment]
And double-check that the helm docs are also regenerated correctly, as this change should also change the README.md.

**Review by Ilyesbdlala — APPROVED** [review]
LGTM. Added needed upgrading notes and created relevant PR that modifies the how-to of cascading scans correspondingly https://github.com/secureCodeBox/documentation/pull/279.

**Comment by Ilyesbdlala** [comment]
> And double-check that the helm docs are also regenerated correctly, as this change should also change the README.md.

Running helm docs manually on the branches is no longer necessary, as they have become since https://github.com/secureCodeBox/secureCodeBox/pull/1291 able to run on and commit to the main branch.

**Pull request merged**
