### PR TITLE
Update list of scantypes for telemetry

### PR DESCRIPTION
**Pull request by malexmave**
Part of #834 - updating the list of official scantypes in the telemetry so we can get a better idea of which scanners are actually being used, so that we can prioritize supporting these scanners as opposed to other scanners that are never actually used.

### CODE REVIEW

**Comment by malexmave** [comment]
https://github.com/secureCodeBox/secureCodeBox/blob/4586eca3b6bc8676c76186396397a42957dae390/operator/internal/telemetry/telemetry.go#L46-L49

Are these still correct? In the scantypes we only have `zap` and `zap-advanced` as scantype names, but I am not sure if ZAP gets special treatment for a reason here.

**Comment by EndPositive** [comment]
@malexmave zap has 3 scantypes declared in its `zap-scan-type.yaml`:

https://github.com/secureCodeBox/secureCodeBox/blob/ae7a050470a586344edc832001a38c2c0bbc962d/scanners/zap/templates/zap-scan-type.yaml#L8

https://github.com/secureCodeBox/secureCodeBox/blob/ae7a050470a586344edc832001a38c2c0bbc962d/scanners/zap/templates/zap-scan-type.yaml#L56

https://github.com/secureCodeBox/secureCodeBox/blob/ae7a050470a586344edc832001a38c2c0bbc962d/scanners/zap/templates/zap-scan-type.yaml#L99

the `zap-advanced` scantype is created in the `zap-advanced` scanner

https://github.com/secureCodeBox/secureCodeBox/blob/ae7a050470a586344edc832001a38c2c0bbc962d/scanners/zap-advanced/templates/zap-advanced-scan-type.yaml#L21

**Comment by malexmave** [comment]
Ah, I see, perfect. In that case this should be ready to go, but it's probably better to wait for an expert for the telemetry code to review this - it's not that urgent anyway :).

**Review by Weltraumschaf — APPROVED** [review]
LGTM

**Review by J12934 — APPROVED** [review]

**Pull request merged**
