### PR TITLE
[SCB-Bot] Upgraded semgrep from 0.85.0 to 0.92.0

### PR DESCRIPTION
**Pull request by secureCodeBoxBot**
This is an automated Pull Request by the SCB-Bot. It upgrades semgrep from 0.85.0 to 0.92.0
### Release changes : [here](https://github.com/returntocorp/semgrep/releases)

### CODE REVIEW

**Comment by malexmave** [comment]
The reason why the CI is failing at this point is because the [semgrep scanner dockerfile is now using the root user](https://github.com/returntocorp/semgrep/pull/4921), and "RunAsNonRoot" is set on our end.

In addition, semgrep [fixed a regression](https://github.com/returntocorp/semgrep/issues/4827) that I had previously [implemented a workaround for](https://github.com/secureCodeBox/secureCodeBox/pull/1048/commits/588f5050baf1fbbad606d364a2bd3f9b48c46ab7), making the workaround harmful.

I set `runAsNonRoot: true` and removed the workaround to fix the issues.

To whoever will review this: Is it okay to have the container run as root, or do we need to have a separate container that we build based on the official one just to change the user the code is running as? According to semgrep, the change to the root user was made because otherwise they [had problems running the image as part of a CI job](https://github.com/returntocorp/semgrep/pull/4921), so it was an intentional change that is unlikely to be reverted soon.

**Comment by J12934** [comment]
It's "ok'ish", it will likely cause the scan type to fail on a lot of clusters as a lot of cluster enforece running as non root.

You can potentially overwrite this semgrep change by using the `runAsUser: <user_id_here>` in pods security context.

**Comment by malexmave** [comment]
I [filed an issue with semgrep](https://github.com/returntocorp/semgrep/issues/5081) (where I also corrected some misconception I had about how this change was introduced, so some of the stuff I wrote above was incorrect). Let's see what the response is there before merging this.

**Comment by malexmave** [comment]
A semgrep dev [confirmed that the change was intentional and will not be reverted](https://github.com/returntocorp/semgrep/issues/5081#issuecomment-1110110982). So, we can either build our own Docker image that simply adds a new user and defaults to using it, or allow the existing image to run as root. Preferences?

**Review by J12934 — APPROVED** [review]

**Comment by J12934** [comment]
@malexmave I've added the breaking label so that we don't forget to put a note about this root change in the release notes

**Pull request merged**
