### PR TITLE
Improve Makefiles for generating scanner documentation

### PR DESCRIPTION
**Pull request by Weltraumschaf**

### CODE REVIEW

**Comment by malexmave** [comment]
Does not seem to work for me...

Test process:
- Check out branch
- Make change to `scanners/gitleaks/.helm-docs.gotmpl`
- In root directory, run `make scanner-docs`
- Process terminates without showing an error code, but READMEs are not updated to reflect the change in the template.

Relevant log snippet:
```
Parser found at: /Users/mmaass/Documents/Code/SecureCodeBox/scanners/gitleaks/parser
INFO[2022-02-02T08:14:04+01:00] Found Chart directories [.]                  
INFO[2022-02-02T08:14:04+01:00] Generating README Documentation for chart /Users/mmaass/Documents/Code/SecureCodeBox/scanners/gitleaks 
WARN[2022-02-02T08:14:04+01:00] Could not open chart README file /Users/mmaass/Documents/Code/SecureCodeBox/scanners/gitleaks/README.md, skipping chart 
Scanner found at: /Users/mmaass/Documents/Code/SecureCodeBox/scanners/gitleaks/scanner
INFO[2022-02-02T08:14:04+01:00] Found Chart directories [.]                  
INFO[2022-02-02T08:14:04+01:00] Generating README Documentation for chart /Users/mmaass/Documents/Code/SecureCodeBox/scanners/gitleaks 
WARN[2022-02-02T08:14:04+01:00] Could not open chart README file /Users/mmaass/Documents/Code/SecureCodeBox/scanners/gitleaks/README.md, skipping chart 
INFO[2022-02-02T08:14:04+01:00] Found Chart directories [.]                  
INFO[2022-02-02T08:14:04+01:00] Generating README Documentation for chart /Users/mmaass/Documents/Code/SecureCodeBox/scanners/gitleaks 
WARN[2022-02-02T08:14:04+01:00] Could not open chart README file /Users/mmaass/Documents/Code/SecureCodeBox/scanners/gitleaks/README.md, skipping chart 
```

Let me know if I can help debug this in any way.

**Comment by Weltraumschaf** [comment]
ACK. I thought this was a general warning, but I cross checked on a Debian machine: No such warnings. I have no clue why it occurs because the printed filename is accessible and I have no idea why helm-docs can't open it.

**Comment by malexmave** [comment]
Maybe @J12934 has an idea what is going on there?

**Comment by Weltraumschaf** [comment]
@J12934 Also something I don't understand: Why is it necessary for`heln-docs` to be executed inside the scanner directory, when I reference all given template files?

**Comment by Weltraumschaf** [comment]
Loglevel trace of`helm-docs` is not helpfull.

**Comment by Weltraumschaf** [comment]
@malexmave Fixed! Would you please test on your machine?

**Comment by malexmave** [comment]
Works on my machine now 🥳

**Review by malexmave — APPROVED** [review]
Works for me, and results are now also consistent with those obtained by the CI job.

**Comment by Weltraumschaf** [comment]
Can you merge? You should have the rights.

**Pull request merged**
