### PR TITLE
Helm Chart: Juice-Shop - Ingress installation failed because of 'apiVersion not set'

### PR DESCRIPTION
**Pull request by fbuchmeier-abi**
## Description

- fixed 'error validating : error validating data: apiVersion not set' when installing with 'ingress.enabled=true'

When enabling the ingress resource, the first `{-` template block would remove the line feeds between the `apiVersion` and the comments at the beginning of the file, causing the `apiVersion` to be omitted and the resource from failing to install.

### Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [NA] Make sure `npm test` runs for the whole project.
* [NA] Make codeclimate checks happy

### CODE REVIEW

**Comment by fuhrmeistery** [comment]
Thanks for your contribution!

Would you please be so kind and sign our DCO as described [here](https://github.com/secureCodeBox/secureCodeBox/blob/main/CONTRIBUTORS.md) and amend the sign-of to your commits?

**Comment by fbuchmeier-abi** [comment]
@fuhrmeistery, thanks for the heads up! I've added the sign-off.

Regards,
Florian.

**Comment by fuhrmeistery** [comment]
@fbuchmeier-abi thanks for adding the sign-off. Could you please also add yourself to the contributors list as described [here](https://github.com/secureCodeBox/secureCodeBox/blob/main/CONTRIBUTORS.md)?
Regards
Yannik

**Comment by fbuchmeier-abi** [comment]
@fuhrmeistery well of course, thanks for babysitting me :+1:

**Review by J12934 — APPROVED** [review]

**Pull request merged**
