### PR TITLE
documentation of ncrack sample corrected (refactoring of 'scannerJob'…

### PR DESCRIPTION
**Pull request by frickeo**
… to 'scanner' missed some docs)

## Description

The documentation for the ncrack sample contains a wrong values structure for adding the ncrack-lists volume and volume-mount. This leads to missing users.txt and passwords.txt files if you follow the sample. In the end the scan runs into 'Errored'.

ncrack-ssh-howto-ncrack-ssh-f6xzf       ncrack              Errored

### Checklist

* [ ] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [ ] Make sure `npm test` runs for the whole project.
* [ ] Make codeclimate checks happy

### CODE REVIEW

**Comment by malexmave** [comment]
Hi @frickeo, and thank you for your pull request!

We're using the [DCO process](https://github.com/secureCodeBox/secureCodeBox/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-and-licensing) here at secureCodeBox, so at the moment, your pull request has a failing CI pipeline. To make it pass, you need to amend your previous commit with a sign-off. You can do this as follows, inside the folder with the Git repo:
```bash
$ git commit --amend -s
# You will see your old commit message again, with a signoff ("signed-off-by") added to it.
# Commit it without changes.
$ git push --force
```

You can also add yourself to the [list of contributors](https://github.com/secureCodeBox/secureCodeBox/blob/main/CONTRIBUTORS.md), as describe in the file linked above. (If you do this in a separate commit, don't forget the signoff using the `-s` flag for `git commit`).

Additionally, it would be great if you could also regenerate the markdown documentation for the scanner you changed, since this is usually done by our CI, but the CI does not run on pull requests from other repos. For this, you need helm-docs. It should be as easy as:
```bash
$ make scanner-docs
```

This should work if you are using Linux. When using Mac OS, the process will likely throw an error, in which case it is probably easier if I generate the docs for you and push them to your branch. Let me know if you would prefer that :). If you generate the docs yourself, don't forget to add the signoff to your commit using the `-s` flag.

**Comment by frickeo** [comment]
Hi Max,
I signed-off my commit and added another one for the list of contributors.

Sadly, I failed to update the markdown documentation. I succeded to run `make scanner-docs` in the main directory, but then a diff contains such an amount of changes that I backed off. I would appreciate if you would regenerate the docs.

Best regards,
Olaf

**Comment by malexmave** [comment]
Hi Olaf,

thanks for making these changes. It seems like you used a different email address for the signoff and for the commit (the commit seems to use your private address while the signoff uses the business address), but that should be fine, I'll set the DCO check to pass :).

It seems like there were no changes to the parts that are generated by the docs command anyway (just checked locally) - sorry, should have checked that before asking you to run it.

So, your PR looks good and I'll be approving and merging it. Thanks again!

**Review by malexmave — APPROVED** [review]

**Comment by malexmave** [comment]
Hi @frickeo, it seems like I forgot that the main branch requires all commits to be GPG-signed. :/

If you have GPG set up with your Git, you can [go through your last commits and sign them](https://superuser.com/a/1123928) (which will require a force-push, but oh well). If you don't have GPG set up, maybe @rseedorff can be convinced to merge through the warning, since the PR just contains a few changes to the documentation?

**Pull request merged**
